# site.yml
---
- name: Install Open Notebook on Fresh Server
  hosts: localhost
  connection: local
  become: yes # Run everything as sudo
  gather_facts: yes # Needed to detect server_ip

  roles:
    - role: docker_install
      tags: ["docker"]
    
    - role: open_notebook
      tags: ["app"]
